### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by pgaddam** [pgaddam/sebc#12]

**Comment by pgaddam** [comment]
Complete cluster setup. 
But importing sample data was timing out. Cluster was very slow!!!
Included screenshot

**Comment by pgaddam** [comment]
Cluster was too slow to run query. During role installation I select "Same as Data Nodes" for node manager. But it ended up installing on only on node which caused slowness

**Comment by pgaddam** [comment]
The slowness issues was with AWS instance. Rebuild AWS instances and cluster started working.
54.219.176.54 ip-172-31-15-77.us-west-1.compute.internal - mysql
54.219.150.15      ip-172-31-0-85.us-west-1.compute.internal - manager
54.153.90.105    ip-172-31-14-164.us-west-1.compute.internal
52.53.164.108    ip-172-31-1-172.us-west-1.compute.internal
54.219.137.13    ip-172-31-10-195.us-west-1.compute.internal

**Comment by mfernest** [comment]
That's an unfair disadvantage. Although the block report that is missing is needed to validate your teragen run -- especially because you cropped the job output a little more than I would like -- I take into account all the extra work necessary to build another cluster. That's an impressive effort in the time allotted.

**INC**omplete.
